// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5g5Rdoqjg7ciSIoJjUxJ32z8vl6CY1Y',
    appId: '1:419845901955:web:88feb0903dfd718d5c55b6',
    messagingSenderId: '419845901955',
    projectId: 'sitiket-54dbb',
    authDomain: 'sitiket-54dbb.firebaseapp.com',
    storageBucket: 'sitiket-54dbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtfuzj3n_cyOK46aLuwJDgZzpuDRYeow',
    appId: '1:419845901955:android:8aef9c2845cbf8e85c55b6',
    messagingSenderId: '419845901955',
    projectId: 'sitiket-54dbb',
    storageBucket: 'sitiket-54dbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAwccOtOb6qLKHwtGe7P2oGmbD6bGdDl0',
    appId: '1:419845901955:ios:5659dfc01b2db15e5c55b6',
    messagingSenderId: '419845901955',
    projectId: 'sitiket-54dbb',
    storageBucket: 'sitiket-54dbb.appspot.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAwccOtOb6qLKHwtGe7P2oGmbD6bGdDl0',
    appId: '1:419845901955:ios:5659dfc01b2db15e5c55b6',
    messagingSenderId: '419845901955',
    projectId: 'sitiket-54dbb',
    storageBucket: 'sitiket-54dbb.appspot.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh5g5Rdoqjg7ciSIoJjUxJ32z8vl6CY1Y',
    appId: '1:419845901955:web:dcbb9154d85adfed5c55b6',
    messagingSenderId: '419845901955',
    projectId: 'sitiket-54dbb',
    authDomain: 'sitiket-54dbb.firebaseapp.com',
    storageBucket: 'sitiket-54dbb.appspot.com',
  );
}
