// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTb6-90UYPu9x-LMWjXUahlLCfbxNz3Ws',
    appId: '1:162436056500:web:1965f2515763331b84dee1',
    messagingSenderId: '162436056500',
    projectId: 'sitiket-yuk',
    authDomain: 'sitiket-yuk.firebaseapp.com',
    databaseURL: 'https://sitiket-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sitiket-yuk.appspot.com',
    measurementId: 'G-WV4TZE8PCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK92r6NJ6OFrpbudlZ__nubqMNIpmoK1U',
    appId: '1:162436056500:android:bb54103ad967608084dee1',
    messagingSenderId: '162436056500',
    projectId: 'sitiket-yuk',
    databaseURL: 'https://sitiket-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sitiket-yuk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATYiAuzukWQJNJmrlQQHhQL0JckPhrpDU',
    appId: '1:162436056500:ios:d139dd7bc8fdd2a684dee1',
    messagingSenderId: '162436056500',
    projectId: 'sitiket-yuk',
    databaseURL: 'https://sitiket-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sitiket-yuk.appspot.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATYiAuzukWQJNJmrlQQHhQL0JckPhrpDU',
    appId: '1:162436056500:ios:d139dd7bc8fdd2a684dee1',
    messagingSenderId: '162436056500',
    projectId: 'sitiket-yuk',
    databaseURL: 'https://sitiket-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sitiket-yuk.appspot.com',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTb6-90UYPu9x-LMWjXUahlLCfbxNz3Ws',
    appId: '1:162436056500:web:1dd49de65a6d123c84dee1',
    messagingSenderId: '162436056500',
    projectId: 'sitiket-yuk',
    authDomain: 'sitiket-yuk.firebaseapp.com',
    databaseURL: 'https://sitiket-yuk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sitiket-yuk.appspot.com',
    measurementId: 'G-GL9XHYLL5N',
  );
}
